### ISSUE TITLE
RFID UIFlow does not load

### ISSUE THREAD

**Issue by Permafrost67** [m5stack/M5-ProductExampleCodes#18]
Hello, when I try to open the RFID file for UIFlow, nothing shows up (it works well with other M5F files).
Also, when using the code from Arduino IDE, it says "no matching function for call to 'MFRC522::MFRC522(int)'".

Can anyone help me with that please?

**Comment by Gitshaoxiang** [comment]
hi , i has test , it seem normal.    maybe your  RFID Program file has some mistake .   

and which one arduino exmaple are you use.?
