### ISSUE TITLE
graphical error in M5StickC slot machine demo

### ISSUE THREAD

**Issue by richard42** [m5stack/M5-ProductExampleCodes#20]
There is a bug in the slot machine demo which causes affects the shadowing effect that is composited on the top and bottom of the spinning slot machine wheels. This bug causes the line on the very first and last row of the screen (which should be the darkest) to be full brightness.

In the file Slot.cpp (inside of the ZIP archive in App/M5StickC_Slot/), line 154 should look like this:

`	for (int i = 0; i < shadowHeight; i++) {`

Currently this for loop starts with "int i = 1", which causes the darkest line of the shadow to have an undefined brightness value.

**Comment by Gitshaoxiang** [comment]
thank you feedback. now it fixed.

https://github.com/m5stack/M5-ProductExampleCodes/tree/master/App/M5StickC_Slot
