### ISSUE TITLE
STEPMOTOR.m5f will not load in UIFlow

### ISSUE THREAD

**Issue by DavidLongley** [m5stack/M5-ProductExampleCodes#23]
I am trying to open the STEPMOTOR.m5f example file found here, and it will not open in UIFlow online or Desktop.
https://github.com/m5stack/M5-ProductExampleCodes/tree/master/AtomBase/Atomic_StepMotor/UIFlow
Please advise.

Regards,
David

**Comment by Gitshaoxiang** [comment]
fixed

**Comment by DavidLongley** [comment]
HI Sean,

I just downloaded again with the same results.
Here is the URL from the M5 Stack documents page.
https://github.com/m5stack/M5-ProductExampleCodes/tree/master/AtomBase/Atomic_StepMotor/UIFlow

Also, I have attached the file.

Is there a different URL?

Regards,
David
