### ISSUE TITLE
AtomicGPS speed of movement - unit of measurement?

### ISSUE THREAD

**Issue by MacLe7400** [m5stack/M5-ProductExampleCodes#24]
Hello,

I'm trying to get speed of movement of GPS module (AtomicGPS) using your example code via `GPS.s_GNRMC.TrackSpeed` parameter from `GPSAnalyse::AnaGPRMC` function in `GPSAnalyse.cpp`.

It seems this parameter returns speed values but in unknown (for me) scale.

I've compare with speed measurement with my car measurement (kmh) and it seems AtomicGPS, results about half of the real speed (there is correlation).

What is unit of measurement returned by this function in example library??

Regards,
M

**Comment by MacLe7400** [comment]
anyone??

**Comment by vkichline** [comment]
Typically, GPS reports speed in knots. One knot = 1.852 KPH.

**Comment by MacLe7400** [comment]
> Typically, GPS reports speed in knots. One knot = 1.852 KPH.

Thank you for answer. 
It seems that simple conversion knots -> kmh delivered proper results
