### ISSUE TITLE
Core2 Factory test bugs (checkI2cAddr())

### ISSUE THREAD

**Issue by tomorrow56** [m5stack/M5-ProductExampleCodes#25]
This function warns that I2C devices are not found.
In the M5Core2 library, Pin definition of Wire and Wire1 are the same and Wire is not valid.

 `
int checkI2cAddr(){
    uint8_t count = 0;
    i2cDevice_t *lastptr = &i2cParentptr;
    do{
        lastptr = lastptr->nextPtr;
        Serial.printf("Addr:0x%02X - Name:%s\r\n",lastptr->addr,lastptr->Name.c_str());
//        Wire.beginTransmission( lastptr->addr );
        Wire1.beginTransmission( lastptr->addr );
//        if ( Wire.endTransmission() == 0 )
        if ( Wire1.endTransmission() == 0 )
        {

 `

**Comment by Gitshaoxiang** [comment]
thank you feedback. already fixed
