### ISSUE TITLE
'struct i2s_config_t' has no member named 'tx_desc_auto_clear'

### ISSUE THREAD

**Issue by koenvervloesem** [m5stack/M5-ProductExampleCodes#26]
Just trying to compile the Core2_Factory_test example code gives me the following error in the Arduino IDE:

```
/home/koan/M5-ProductExampleCodes/Core/M5Core2/Arduino/Core2_Factory_test/Core2_Factory_test.ino: In function 'bool InitI2SSpakerOrMic(int)':
Core2_Factory_test:304:20: error: 'struct i2s_config_t' has no member named 'tx_desc_auto_clear'
         i2s_config.tx_desc_auto_clear = true;
```

This is on Arduino 1.8.13 with the esp32 1.0.4 board support from Espressif, and the M5Core2 0.0.1 library installed.

Any pointers to what could be wrong?

**Comment by vany5921** [comment]
There is no problem compiling. You can try to update the latest esp32 dependency library or comment out this sentence directly

**Comment by koenvervloesem** [comment]
Thanks, I reinstalled the whole Arduino stack and now it compiles successfully.
