### ISSUE TITLE
When will Thermal camera support on M5core2?

### ISSUE THREAD

**Issue by fermintm** [m5stack/M5-ProductExampleCodes#31]
When will Thermal camera support on M5core2?

**Comment by Gitshaoxiang** [comment]
Do you mean the MLX96640? the Thermal Unit?  We will add the transplanted program as soon as possible。  before we release it, you could refer to this program for Core2. but before you compile it, you need to change the lib(use M5Core2.h).

https://github.com/m5stack/M5Stack/tree/master/examples/Unit/THERMAL_MLX90640
