### ISSUE TITLE
Unit-Key_noBlock.m5f is not m5f but HTML

### ISSUE THREAD

**Issue by 3110** [m5stack/M5-ProductExampleCodes#51]
https://github.com/m5stack/M5-ProductExampleCodes/blob/master/Unit/KEY/UIFLOW/Unit-Key_noBlock.m5f

The UiFlow sample of Unit Key is not the m5f file but the HTML file.

[![Image from Gyazo](https://i.gyazo.com/c116ed205aed5772a74ee1a7f5722a55.png)](https://gyazo.com/c116ed205aed5772a74ee1a7f5722a55)

**Comment by IcingTomato** [comment]
You can right click and "Save as..." to save as *.m5f file.

**Comment by 3110** [comment]
If you mean the UiFlow sample of Unit Key is the same as Unit Limit, you shoud commit the following JSON file as m5f file not HTML file of the GitHub page.

https://raw.githubusercontent.com/m5stack/M5-ProductExampleCodes/master/Unit/LIMIT/UIFlow/Unit-Limit_noBlock.m5f

**Comment by Tinyu-Zhao** [comment]
> If you mean the UiFlow sample of Unit Key is the same as Unit Limit, you shoud commit the following JSON file as m5f file not HTML file of the GitHub page.
> 
> https://raw.githubusercontent.com/m5stack/M5-ProductExampleCodes/master/Unit/LIMIT/UIFlow/Unit-Limit_noBlock.m5f

GitHub doesn't support .m5f format files, not that I want him to be in HTML format, and the content of the .m5f format file itself is such that you can try keeping a .m5f on UIFLOW yourself

**Comment by IcingTomato** [comment]
I will upload a new one from our FAE.

**Comment by IcingTomato** [comment]
#52 I add KEY and KEY&LIMIT example. If there are any problem, please re-open this issue. Thank you for your cooperation.
