### ISSUE TITLE
ENV code not working

### ISSUE THREAD

**Issue by bert2002** [m5stack/M5-ProductExampleCodes#8]
Hi,
just got my ENV unit and wanted to bring it alive with my M5stack and unfortunately it is not working. The example code in `Unit/ENV/Arduino/ENV/ENV.ino` gives me this:

```
20:39:16.008 -> M5Stack initializing...OK
20:39:16.650 -> ENV Unit(DHT12 and BMP280) test...
20:39:16.650 -> Could not find a valid BMP280 sensor, check wiring!
```
When I try my own code on it with following code:
```
if (!bme.begin(0x76)){  
      Serial.println("Could not find a valid BMP280 sensor, check wiring!");
      while (1);
    }
```
Then it will work.

**Comment by graydonli** [comment]
Thanks, I updated this example code.
